<?php

namespace CV\UserBundle\Repository;

/**
 * RIRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RIRepository extends \Doctrine\ORM\EntityRepository
{
}
