# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    CV\UserBundle\Entity\RI: plaintext

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    main:
      entity:
        class:    CV\UserBundle\Entity\RI
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern:      ^/
      anonymous:    true
      provider:  main 
      form_login:
        login_path: login
        check_path: login_check
      logout:
        path:       logout
        target:     login

  access_control:
  - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
  - { path: ^/profils, role: ROLE_USER }
