<?php

namespace CV\ProfilBundle\Repository;

/**
 * Bloc_libre1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Bloc_libre1Repository extends \Doctrine\ORM\EntityRepository
{
}
