<?php

namespace CV\ProfilBundle\Repository;

/**
 * CVRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CVRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAll()
    {
        return $this->findBy(array(), array('dateCrea' => 'DESC'));
    }
}
