<?php

namespace CV\ProfilBundle\Repository;

/**
 * DomainesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomainesRepository extends \Doctrine\ORM\EntityRepository
{
}
