<?php

namespace CV\ProfilBundle\Repository;

/**
 * InterlocuteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterlocuteurRepository extends \Doctrine\ORM\EntityRepository
{
}
