<?php

namespace CV\ProfilBundle\Repository;

/**
 * ProfilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilRepository extends \Doctrine\ORM\EntityRepository
{

	public function findAll()
    {
        return $this->findBy(array(), array('dateCrea' => 'DESC'));
    }
    
}
