<?php

namespace CV\ProfilBundle\Repository;

/**
 * Type_clientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_clientRepository extends \Doctrine\ORM\EntityRepository
{
}
